### testing get climatecodes

GET http://localhost:5000/climatecodes/

### testing get climatecodes af

GET http://localhost:5000/climatecodes/Af

### testing get forecast

GET http://localhost:5000/forecasts/

### testing get forecast with name

GET http://localhost:5000/forecasts/Arjeplog/

### testing get forecast with fromtime

GET http://localhost:5000/forecasts/Uppsala/2020-01-02 06:00:00

### testing get usernames

GET http://localhost:5000/users/

### testing get usernames with names

GET http://localhost:5000/users/Glenn Nilsson

### testing adding user Glenn Nilsson

POST http://localhost:5000/users/
Content-Type: application/json

{
    "id": "3",
    "username": "Glenn Nilsson",
    "email": "glen@swnet.se",
    "favlocation": "Arjeplog"
}


